name: iso
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build iso
    runs-on: ubuntu-latest
    steps:
      - uses: ilammy/setup-nasm@v1
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build iso
        run:  cd tools && ./build.sh && ./iso.sh
      - name: Upload iso
        uses: actions/upload-artifact@v4
        with:
          name: os.iso
          path: 'build/os.iso'
