name: iso
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build iso
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: mtools
          version: 1.0
      - uses: ilammy/setup-nasm@v1
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build iso
        run:  cd tools && ./build.sh && ./iso.sh ./cmake-build-debug/kernel
      - name: Upload iso
        uses: actions/upload-artifact@v4
        with:
          name: os.iso
          path: 'build/os.iso'
