name: test
on:
  pull_request:

jobs:
  test:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build and Run Tests
        run:  cd tools && ./runtests.sh
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always() # always run even if the previous step fails
        with:
          name: junit-test-results
          path: '**/build-tests/report/*.xml'
          retention-days: 1
